CREATE DATABASE IF NOT EXISTS biblioteca_digital;
USE biblioteca_digital;

CREATE TABLE USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    ape1 VARCHAR(50) NOT NULL,
    ape2 VARCHAR(50),
    rol ENUM('registrado', 'administrador') NOT NULL
);

CREATE TABLE LIBROS (
    ISBN VARCHAR(13) PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL
);

CREATE TABLE PRESTAMOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ISBN VARCHAR(13) NOT NULL,
    id_usuario INT NOT NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NOT NULL,
    FOREIGN KEY (ISBN) REFERENCES LIBROS(ISBN),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
);

CREATE TABLE RESERVAS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ISBN VARCHAR(13) NOT NULL,
    id_usuario INT NOT NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NOT NULL,
    FOREIGN KEY (ISBN) REFERENCES LIBROS(ISBN),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
);
